---
include:
  - "**/*.rb"
  - "**/*.rake"
  - "**/*.ru"
  - "**/Rakefile"
  - "**/Gemfile"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - "node_modules/**/*"
require: []
domains: []
reporters:
- rubocop
plugins: []
max_files: 5000
