version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manage_server_development
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:6.2
    networks:
      - backend

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    networks:
      - backend
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -e development
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
