services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manage_server_development
    networks:
      - backend

  redis:
    image: redis:6.2
    networks:
      - backend

  sidekiq:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - ..:/myapp
    networks:
      - backend
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0' -e development
    volumes:
      - ..:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
